CREATE TABLE IF NOT EXISTS user (
  user_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1),
  active INTEGER DEFAULT NULL,
  email varchar(255) NOT NULL,
  last_name varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  PRIMARY KEY (user_id)
);
CREATE TABLE IF NOT EXISTS role (
  role_id INTEGER NOT NULL,
  role varchar(255) DEFAULT NULL,
  PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS user_role (
  user_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL,
  PRIMARY KEY (role_id, user_id)
);

CREATE TABLE IF NOT EXISTS user_skill (
	user_id INTEGER NOT NULL,
 	skill_id INTEGER NOT NULL,
	PRIMARY KEY (user_id,skill_id)
);
CREATE TABLE IF NOT EXISTS skill (
 	skill_id INTEGER NOT NULL,
	name varchar(20) NOT NULL,
	PRIMARY KEY (skill_id)
);
CREATE TABLE IF NOT EXISTS vacation (
 	user_id INTEGER NOT NULL,
	day date NOT NULL,
	PRIMARY KEY (user_id, day)
);
